/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Personal Finance Manager API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface BudgetAlert {
  budgetId: number;
  budgetName: string;
  allocated: number;
  spent: number;
  percentage: number;
  isOverBudget: boolean;
}

export interface DashboardSummary {
  totalBalance: number;
  monthlyIncome: number;
  monthlyExpense: number;
  monthlySavings: number;
  budgetAlerts: BudgetAlert[];
  totalSavings: number;
}

export interface Budget {
  id: number;
  name: string;
  category: string;
  allocatedAmount: number;
  spentAmount: number;
  remainingAmount: number;
  color: string;
  month: number;
  year: number;
  createdAt: string;
}

export interface CreateBudgetInput {
  name: string;
  category: string;
  allocatedAmount: number;
  color?: string;
  month: number;
  year: number;
}

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionType = {
  income: "income",
  expense: "expense",
} as const;

export interface Transaction {
  id: number;
  budgetId?: number;
  budgetName?: string;
  type: TransactionType;
  amount: number;
  description: string;
  date: string;
  createdAt: string;
}

export type CreateTransactionInputType =
  (typeof CreateTransactionInputType)[keyof typeof CreateTransactionInputType];

export const CreateTransactionInputType = {
  income: "income",
  expense: "expense",
} as const;

export interface CreateTransactionInput {
  budgetId?: number;
  type: CreateTransactionInputType;
  amount: number;
  description: string;
  date: string;
}

export interface SavingsAccount {
  id: number;
  name: string;
  balance: number;
  targetAmount?: number;
  description?: string;
  createdAt: string;
}

export interface CreateSavingsAccountInput {
  name: string;
  balance: number;
  targetAmount?: number;
  description?: string;
}

export interface UpdateSavingsAccountInput {
  name?: string;
  balance?: number;
  targetAmount?: number;
  description?: string;
}

export interface MonthlySummaryItem {
  month: string;
  income: number;
  expense: number;
}

export type GetTransactionsParams = {
  month?: number;
  year?: number;
  budgetId?: number;
  type?: GetTransactionsType;
};

export type GetTransactionsType =
  (typeof GetTransactionsType)[keyof typeof GetTransactionsType];

export const GetTransactionsType = {
  income: "income",
  expense: "expense",
} as const;

export type GetMonthlySummaryParams = {
  months?: number;
};
